### ISSUE TITLE
cannot read 'includes'

### ISSUE THREAD

**Issue by cadburry6969** [Skeexs/skeexsNotify#1]
![image](https://user-images.githubusercontent.com/72443203/130910352-32031000-71de-4b46-b026-47258d6fbc94.png)

**Comment by SoraTogaGaming** [comment]
Sorry If I'm missing the hint but did you manage to find out how to get past the error?

**Comment by cadburry6969** [comment]
> Sorry If I'm missing the hint but did you manage to find out how to get past the error?

no error just people got confused with readme
