### ISSUE TITLE
Using sounds when notification pops

### ISSUE THREAD

**Issue by cometopudgeee** [Skeexs/skeexsNotify#4]
how to play sound when theres a notification

**Comment by MrMillxr** [comment]
> how to play sound when theres a notification

Hi, on FiveM the Native is `PlaySoundFrontend` 

And Example of how to modify the script is 
```
RegisterNetEvent('skeexsNotify:client:SendAlert')
AddEventHandler('skeexsNotify:client:SendAlert', function(DATA)
	TriggerNotification(DATA)
	PlaySoundFrontend(-1, 'Click', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 0)
end)
```

Enjoy :)

**Comment by Skeexs** [comment]
This now comes directly in the script and no more needs to be added by yourself :)
