### ISSUE TITLE
How do i update the bootstrap link? 

### ISSUE THREAD

**Issue by MrMillxr** [Skeexs/skeexsNotify#5]
I can see in the ui.html that the stylesheet is bootstrap 1.3.0, but the latest version is on 1.9.1, how do i update this for better  icons?

**Comment by Vacsson** [comment]
> I can see in the ui.html that the stylesheet is bootstrap 1.3.0, but the latest version is on 1.9.1, how do i update this for better icons?

By replacing the link with the newest one.

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css"/>`

**Comment by Skeexs** [comment]
Updated.
