### ISSUE TITLE
change message location

### ISSUE THREAD

**Issue by mrstruggle93** [Skeexs/skeexsNotify#6]
how do i change the location of the message, like TOP-Right

**Comment by Vacsson** [comment]
> how do i change the location of the message, like TOP-Right

I solved it by adding:

  position: absolute;
  top: 3px;
  right: 5px;

under #root .main .notification

This is probably not the correct way to fix it for it to work for everyone, but in my case it worked correctly.
_CSS is not really my thing..._

**Comment by Skeexs** [comment]
Working on it
